# Don't print a new line at the start of the prompt
add_newline = false

[character]
success_symbol = "[➜](green) "
error_symbol = "[✗](red) "

[line_break]
disabled = true

[git_status]
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇡$ahead_count ⇣$behind_count"

[username]
show_always = true

[directory]
truncation_length = 2
fish_style_pwd_dir_length = 1

[package]
disabled = true

[java]
style = "green"

